# -*- coding: utf-8 -*-
"""Soccer_Object Detection_Training_Optimization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18AcTe0ar-QbNnMExjW13dbt5IjIAgo-7

# Training Optimization for 2D Object Detection
## Soccer/Football Player Detection — YOLOv8

### Experiments:
1. **Exp 1:** Baseline (YOLOv8n, default settings)
2. **Exp 2:** Architecture modification (YOLOv8n → YOLOv8s)
3. **Exp 3:** Training strategy optimization
4. **Exp 4:** Full optimization + custom annotated data
5. COCO-style evaluation comparison

**Runtime → Change runtime type → H100 GPU**
"""

!pip install --upgrade ultralytics roboflow pycocotools pandas seaborn matplotlib albumentations -q

"""---
## Step 1: Download BASE Dataset
"""

from roboflow import Roboflow
import os, yaml

API_KEY = "9SYwXIvGuwcnanu5YY8g"

rf = Roboflow(api_key=API_KEY)
project = rf.workspace("roboflow-jvuqo").project("football-players-detection-3zvbc")
dataset = project.version(1).download("yolov8")

BASE_PATH = dataset.location
BASE_YAML = os.path.join(BASE_PATH, 'data.yaml')

print(f"Base dataset: {BASE_PATH}")
print(f"data.yaml exists: {os.path.exists(BASE_YAML)}")
for split in ['train', 'valid', 'test']:
    d = os.path.join(BASE_PATH, split, 'images')
    if os.path.exists(d):
        print(f"  {split}: {len(os.listdir(d))} images")

"""---
## Step 2: Download CUSTOM Dataset (Smart Football Object Detection)

Downloads from the **smart-football-object-detection** project, then selects ~161 images organized by class for our custom annotations.
"""

import os, shutil, json, yaml, zipfile
from collections import defaultdict, Counter
from roboflow import Roboflow

API_KEY = "9SYwXIvGuwcnanu5YY8g"

# STEP A: Download the dataset
rf2 = Roboflow(api_key=API_KEY)
project2 = rf2.workspace("smart-football-object-detection").project("smart-football-object-detection")
version = project2.version(11)
dataset2 = version.download("yolov8")

print(f"Reported location: {dataset2.location}")
print(f"Top-level contents: {os.listdir(dataset2.location)}")

# STEP B: Handle unextracted zip if present
zip_path = os.path.join(dataset2.location, "roboflow.zip")
if os.path.exists(zip_path):
    print("Found roboflow.zip — extracting...")
    with zipfile.ZipFile(zip_path, 'r') as z:
        z.extractall(dataset2.location)
    os.remove(zip_path)
    print(f"Extracted! Contents now: {os.listdir(dataset2.location)}")

# STEP C: Find data.yaml (could be at top level or in subfolder)
yaml_path = None
for root, dirs, files in os.walk(dataset2.location):
    if "data.yaml" in files:
        yaml_path = os.path.join(root, "data.yaml")
        break

if not yaml_path:
    # Last resort: check if train/images exists directly
    if os.path.isdir(os.path.join(dataset2.location, "train", "images")):
        print("No data.yaml found but train/images exists — creating data.yaml")
        yaml_path = os.path.join(dataset2.location, "data.yaml")
        auto_yaml = {
            'path': os.path.abspath(dataset2.location),
            'train': 'train/images',
            'val': 'valid/images',
            'test': 'test/images',
            'nc': 4,
            'names': ['ball', 'goalkeeper', 'player', 'referee']
        }
        with open(yaml_path, 'w') as f:
            yaml.dump(auto_yaml, f)
    else:
        # Print everything to debug
        print("\nFull directory tree:")
        for root, dirs, files in os.walk(dataset2.location):
            level = root.replace(dataset2.location, '').count(os.sep)
            indent = '  ' * level
            print(f"{indent}{os.path.basename(root)}/")
            if level < 3:
                for f in files[:10]:
                    print(f"{indent}  {f}")
        raise FileNotFoundError(f"Cannot find data.yaml or train/images under {dataset2.location}")

CUSTOM_ROOT = os.path.dirname(yaml_path)
print(f"\ndata.yaml found at: {yaml_path}")
print(f"Custom root: {CUSTOM_ROOT}")

# STEP D: Parse classes
with open(yaml_path, "r") as f:
    data_cfg = yaml.safe_load(f)

class_names = data_cfg["names"]
if isinstance(class_names, dict):
    class_names = [class_names[i] for i in sorted(class_names.keys())]
name_to_id = {name.lower(): idx for idx, name in enumerate(class_names)}
print(f"Classes: {name_to_id}")

# STEP E: Scan all images and their labels
TARGETS = {"ball": 65, "goalkeeper": 37, "referee": 37, "player": 22}

image_classes = defaultdict(set)
image_paths = {}

for split in ["train", "valid", "test"]:
    img_dir = os.path.join(CUSTOM_ROOT, split, "images")
    label_dir = os.path.join(CUSTOM_ROOT, split, "labels")
    if not os.path.isdir(img_dir):
        continue
    for img_file in os.listdir(img_dir):
        if not img_file.lower().endswith((".jpg", ".jpeg", ".png")):
            continue
        stem = os.path.splitext(img_file)[0]
        img_path = os.path.join(img_dir, img_file)
        label_path = os.path.join(label_dir, stem + ".txt")
        if not os.path.exists(label_path):
            continue
        with open(label_path) as lf:
            for line in lf:
                line = line.strip()
                if not line:
                    continue
                cls_id = int(line.split()[0])
                if cls_id < len(class_names):
                    image_classes[stem].add(class_names[cls_id].lower())
        image_paths[stem] = (img_path, label_path)

print(f"\nTotal annotated images: {len(image_paths)}")
all_cls = [c for cs in image_classes.values() for c in cs]
print(f"Class distribution: {Counter(all_cls)}")

# STEP F: Select images per category
import random
random.seed(42)

already_selected = set()
selected_per_cat = defaultdict(list)

for cat, quota in TARGETS.items():
    matched_key = next((k for k in name_to_id if cat in k or k in cat), None)
    if matched_key is None:
        print(f"WARNING: '{cat}' not found in {list(name_to_id.keys())}")
        continue
    candidates = [
        stem for stem, classes in image_classes.items()
        if matched_key in classes and stem not in already_selected
    ]
    candidates.sort(key=lambda s: len(image_classes[s]))
    chosen = candidates[:quota]
    selected_per_cat[cat].extend(chosen)
    already_selected.update(chosen)
    print(f"  {cat:12s}: requested={quota}, available={len(candidates)}, selected={len(chosen)}")

# STEP G: Copy to organized output folder
OUTPUT_DIR = "./selected_annotation_dataset"
if os.path.exists(OUTPUT_DIR):
    shutil.rmtree(OUTPUT_DIR)

for cat, stems in selected_per_cat.items():
    cat_img_dir = os.path.join(OUTPUT_DIR, cat, "images")
    cat_label_dir = os.path.join(OUTPUT_DIR, cat, "labels")
    os.makedirs(cat_img_dir, exist_ok=True)
    os.makedirs(cat_label_dir, exist_ok=True)
    for stem in stems:
        img_src, lbl_src = image_paths[stem]
        shutil.copy(img_src, os.path.join(cat_img_dir, os.path.basename(img_src)))
        shutil.copy(lbl_src, os.path.join(cat_label_dir, stem + ".txt"))

manifest = {
    "total_selected": len(already_selected),
    "source_classes": class_names,
    "categories": {cat: stems for cat, stems in selected_per_cat.items()}
}
with open(os.path.join(OUTPUT_DIR, "manifest.json"), "w") as f:
    json.dump(manifest, f, indent=2)

print(f"\n✅ Done! {len(already_selected)} images → {OUTPUT_DIR}")
for cat, stems in selected_per_cat.items():
    print(f"   {cat}: {len(stems)} images")

"""---
## Step 3: Merge Base + Custom into One Dataset
"""

import shutil, random, yaml, os, json

MERGED_PATH = "merged_dataset"
if os.path.exists(MERGED_PATH):
    shutil.rmtree(MERGED_PATH)

for split in ['train', 'valid', 'test']:
    os.makedirs(f"{MERGED_PATH}/{split}/images", exist_ok=True)
    os.makedirs(f"{MERGED_PATH}/{split}/labels", exist_ok=True)

# ── Read base class names ──
with open(BASE_YAML, 'r') as f:
    base_cfg = yaml.safe_load(f)
base_names = base_cfg['names']
if isinstance(base_names, dict):
    base_names = [base_names[i] for i in sorted(base_names.keys())]
base_name_to_id = {n.lower(): i for i, n in enumerate(base_names)}
print(f"Base classes: {base_name_to_id}")

# ── Read custom class names ──
with open(yaml_path, 'r') as f:
    custom_cfg = yaml.safe_load(f)
custom_names = custom_cfg['names']
if isinstance(custom_names, dict):
    custom_names = [custom_names[i] for i in sorted(custom_names.keys())]
custom_id_to_name = {i: n.lower() for i, n in enumerate(custom_names)}
print(f"Custom classes: {custom_id_to_name}")

# ── Build class ID remapping: custom_id → base_id ──
remap = {}
for cid, cname in custom_id_to_name.items():
    if cname in base_name_to_id:
        remap[cid] = base_name_to_id[cname]
    else:
        match = next((bn for bn in base_name_to_id if cname in bn or bn in cname), None)
        if match:
            remap[cid] = base_name_to_id[match]
        else:
            print(f"  ⚠️ Cannot map '{cname}' (id={cid}) — will skip these annotations")
print(f"Remapping: {remap}")

# ── Copy base dataset ──
print("\nCopying base dataset...")
for split in ['train', 'valid', 'test']:
    for subdir in ['images', 'labels']:
        src = os.path.join(BASE_PATH, split, subdir)
        dst = f"{MERGED_PATH}/{split}/{subdir}"
        if os.path.exists(src):
            for f in os.listdir(src):
                shutil.copy2(os.path.join(src, f), os.path.join(dst, f))

# ── Flatten custom dataset and add with remapped IDs ──
print("Adding custom images with remapped class IDs...")
custom_dir = "./selected_annotation_dataset"
all_custom_pairs = []

for cat in os.listdir(custom_dir):
    cat_img = os.path.join(custom_dir, cat, "images")
    cat_lbl = os.path.join(custom_dir, cat, "labels")
    if not os.path.isdir(cat_img):
        continue
    for img_file in os.listdir(cat_img):
        if not img_file.lower().endswith(('.jpg', '.jpeg', '.png')):
            continue
        stem = os.path.splitext(img_file)[0]
        lbl_path = os.path.join(cat_lbl, stem + '.txt')
        if os.path.exists(lbl_path):
            all_custom_pairs.append((os.path.join(cat_img, img_file), lbl_path))

print(f"Found {len(all_custom_pairs)} custom image-label pairs")

# Shuffle and split 80/20
random.seed(42)
random.shuffle(all_custom_pairs)
split_idx = int(0.8 * len(all_custom_pairs))
train_pairs = all_custom_pairs[:split_idx]
val_pairs = all_custom_pairs[split_idx:]

added = 0
skipped = 0
for pairs, split in [(train_pairs, 'train'), (val_pairs, 'valid')]:
    for img_path, lbl_path in pairs:
        img_name = os.path.basename(img_path)
        stem = os.path.splitext(img_name)[0]
        dst_img = f"{MERGED_PATH}/{split}/images/custom_{img_name}"
        dst_lbl = f"{MERGED_PATH}/{split}/labels/custom_{stem}.txt"

        # Read and remap labels
        with open(lbl_path, 'r') as f:
            lines = f.readlines()

        remapped = []
        for line in lines:
            parts = line.strip().split()
            if len(parts) >= 5:
                old_id = int(parts[0])
                if old_id in remap:
                    remapped.append(f"{remap[old_id]} {' '.join(parts[1:])}")

        if remapped:
            shutil.copy2(img_path, dst_img)
            with open(dst_lbl, 'w') as f:
                f.write('\n'.join(remapped))
            added += 1
        else:
            skipped += 1

# ── Write merged data.yaml ──
merged_yaml = {
    'path': os.path.abspath(MERGED_PATH),
    'train': 'train/images',
    'val': 'valid/images',
    'test': 'test/images',
    'nc': len(base_names),
    'names': base_names
}
MERGED_YAML = f"{MERGED_PATH}/data.yaml"
with open(MERGED_YAML, 'w') as f:
    yaml.dump(merged_yaml, f, default_flow_style=False)

# ── Summary ──
print(f"\n{'='*50}")
print("MERGED DATASET SUMMARY")
print(f"{'='*50}")
for split in ['train', 'valid', 'test']:
    d = f"{MERGED_PATH}/{split}/images"
    if os.path.exists(d):
        print(f"  {split}: {len(os.listdir(d))} images")
print(f"  Custom added: {added} | Skipped: {skipped}")
print(f"  YAML: {MERGED_YAML}")

"""---
## Step 4: Explore Merged Dataset
"""

import matplotlib.pyplot as plt
from collections import Counter
import numpy as np

label_dir = f"{MERGED_PATH}/train/labels"
class_counts = Counter()
for lf in os.listdir(label_dir):
    if not lf.endswith('.txt'): continue
    with open(os.path.join(label_dir, lf)) as fh:
        for line in fh:
            parts = line.strip().split()
            if len(parts) >= 5:
                class_counts[int(parts[0])] += 1

names = [base_names[i] for i in sorted(class_counts.keys())]
counts = [class_counts[i] for i in sorted(class_counts.keys())]

print("Merged train set class distribution:")
for n, c in zip(names, counts):
    print(f"  {n}: {c} instances")

plt.figure(figsize=(8, 4))
plt.bar(names, counts, color=['#FF6B6B', '#4ECDC4', '#45B7D1', '#96CEB4'])
plt.title('Merged Dataset — Class Distribution (Train)')
plt.ylabel('Instances')
plt.show()

"""---
# TRAINING EXPERIMENTS

| # | Experiment | Dataset | Model | Key Changes |
|---|---|---|---|---|
| 1 | Baseline | Base | YOLOv8n | All defaults |
| 2 | Architecture | Base | YOLOv8s | 3.5x more parameters |
| 3 | Strategy | Base | YOLOv8s | AdamW, augmentations, bigger images |
| 4 | Full + Custom | **Merged** | YOLOv8s | + custom annotated images |

## Experiment 1: Baseline (YOLOv8n)
"""

from ultralytics import YOLO

print("="*60)
print("EXPERIMENT 1: BASELINE (YOLOv8n, default settings)")
print("="*60)

model_1 = YOLO('yolov8n.pt')
model_1.train(
    data=BASE_YAML, epochs=50, imgsz=640, batch=16,
    name='exp1_baseline', project='soccer_results', seed=42,
    optimizer='SGD', lr0=0.01, lrf=0.01, momentum=0.937,
    weight_decay=0.0005, warmup_epochs=3.0,
    mosaic=1.0, mixup=0.0, copy_paste=0.0, degrees=0.0,
    translate=0.1, scale=0.5, fliplr=0.5,
    hsv_h=0.015, hsv_s=0.7, hsv_v=0.4,
    box=7.5, cls=0.5, dfl=1.5,
)
m1 = model_1.val()
print(f"\n✅ BASELINE: mAP50={m1.box.map50:.4f} mAP50-95={m1.box.map:.4f} P={m1.box.mp:.4f} R={m1.box.mr:.4f}")

"""## Experiment 2: Architecture Modification (YOLOv8s)

**Change:** YOLOv8n (3.2M params) → YOLOv8s (11.2M params)

**Why:** More capacity for complex soccer scenes with overlapping players and tiny ball.
"""

print("="*60)
print("EXPERIMENT 2: ARCHITECTURE (YOLOv8s)")
print("="*60)

model_2 = YOLO('yolov8s.pt')
model_2.train(
    data=BASE_YAML, epochs=50, imgsz=640, batch=16,
    name='exp2_architecture', project='soccer_results', seed=42,
)
m2 = model_2.val()
print(f"\n✅ ARCH: mAP50={m2.box.map50:.4f} mAP50-95={m2.box.map:.4f} P={m2.box.mp:.4f} R={m2.box.mr:.4f}")

"""## Experiment 3: Training Strategy Optimization

**Augmentation:** Mixup 0.15, CopyPaste 0.1, Rotation ±10°, Erasing 0.3

**Optimizer:** AdamW + Cosine LR

**Other:** Image size 736, label smoothing 0.1, warmup 5 epochs
"""

print("="*60)
print("EXPERIMENT 3: TRAINING STRATEGY OPTIMIZATION")
print("="*60)

model_3 = YOLO('yolov8s.pt')
model_3.train(
    data=BASE_YAML, epochs=80, patience=15, imgsz=736, batch=12,
    name='exp3_strategy', project='soccer_results', seed=42,
    mosaic=1.0, mixup=0.15, copy_paste=0.1, degrees=10.0,
    translate=0.2, scale=0.9, fliplr=0.5,
    hsv_h=0.02, hsv_s=0.8, hsv_v=0.5, erasing=0.3,
    optimizer='AdamW', lr0=0.001, lrf=0.01,
    weight_decay=0.0005, warmup_epochs=5, cos_lr=True,
    label_smoothing=0.1,
    box=7.5, cls=1.0, dfl=1.5, close_mosaic=10,
)
m3 = model_3.val()
print(f"\n✅ STRATEGY: mAP50={m3.box.map50:.4f} mAP50-95={m3.box.map:.4f} P={m3.box.mp:.4f} R={m3.box.mr:.4f}")

"""## Experiment 4: Full Optimization + Custom Data

Same optimized settings as Exp 3, trained on the **merged dataset** (base + custom annotated images).
"""

print("="*60)
print("EXPERIMENT 5: YOLOv8s + CUSTOM DATA (default training)")
print("="*60)

model_5 = YOLO('yolov8s.pt')
model_5.train(
    data=MERGED_YAML, epochs=50, imgsz=640, batch=16,
    name='exp5_arch_custom', project='soccer_results', seed=42,
)
m5 = model_5.val()
print(f"\n✅ ARCH+CUSTOM: mAP50={m5.box.map50:.4f} mAP50-95={m5.box.map:.4f} P={m5.box.mp:.4f} R={m5.box.mr:.4f}")

print("="*60)
print("EXPERIMENT 4: FULL OPTIMIZATION + CUSTOM DATA")
print("="*60)

model_4 = YOLO('yolov8s.pt')
model_4.train(
    data=MERGED_YAML, epochs=80, patience=15, imgsz=736, batch=12,
    name='exp4_full_custom', project='soccer_results', seed=42,
    mosaic=1.0, mixup=0.15, copy_paste=0.1, degrees=10.0,
    translate=0.2, scale=0.9, fliplr=0.5,
    hsv_h=0.02, hsv_s=0.8, hsv_v=0.5, erasing=0.3,
    optimizer='AdamW', lr0=0.001, lrf=0.01,
    weight_decay=0.0005, warmup_epochs=5, cos_lr=True,
    label_smoothing=0.1,
    box=7.5, cls=1.0, dfl=1.5, close_mosaic=10,
)
m4 = model_4.val()
print(f"\n✅ FULL+CUSTOM: mAP50={m4.box.map50:.4f} mAP50-95={m4.box.map:.4f} P={m4.box.mp:.4f} R={m4.box.mr:.4f}")

"""---
# COCO-Style Evaluation & Comparison
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

print("="*70)
print("COCO-STYLE EVALUATION COMPARISON")
print("="*70)

results = {
    'Experiment': [
        '1. Baseline (YOLOv8n)',
        '2. Architecture (YOLOv8s)',
        '3. Strategy Optimized',
        '4. Full + Custom Data',
        '5. Arch + Custom (no strategy)',
    ],
    'mAP50': [m1.box.map50, m2.box.map50, m3.box.map50, m4.box.map50, m5.box.map50],
    'mAP50-95': [m1.box.map, m2.box.map, m3.box.map, m4.box.map, m5.box.map],
    'Precision': [m1.box.mp, m2.box.mp, m3.box.mp, m4.box.mp, m5.box.mp],
    'Recall': [m1.box.mr, m2.box.mr, m3.box.mr, m4.box.mr, m5.box.mr],
}

df = pd.DataFrame(results)
df_disp = df.copy()
for col in ['mAP50', 'mAP50-95', 'Precision', 'Recall']:
    df_disp[col] = df_disp[col].apply(lambda x: f'{x:.4f}')
print("\n" + df_disp.to_string(index=False))
df.to_csv('experiment_comparison.csv', index=False)
print("\nSaved to experiment_comparison.csv")

# === CHARTS (now 5 experiments) ===
fig, axes = plt.subplots(1, 3, figsize=(22, 6))
labels = ['Baseline\n(YOLOv8n)', 'Arch Mod\n(YOLOv8s)', 'Strategy\nOptimized', 'Full +\nCustom', 'Arch +\nCustom']
colors = ['#FF6B6B', '#4ECDC4', '#45B7D1', '#96CEB4', '#DDA0DD']

x = np.arange(5)
w = 0.35
axes[0].bar(x - w/2, df['mAP50'], w, label='mAP50', color='#45B7D1')
axes[0].bar(x + w/2, df['mAP50-95'], w, label='mAP50-95', color='#FF6B6B')
axes[0].set_xticks(x)
axes[0].set_xticklabels(labels, fontsize=8)
axes[0].set_ylabel('Score')
axes[0].set_title('mAP Comparison Across Experiments')
axes[0].legend()
axes[0].set_ylim(0, 1)
for i, (v1, v2) in enumerate(zip(df['mAP50'], df['mAP50-95'])):
    axes[0].text(i - w/2, v1 + 0.02, f'{v1:.3f}', ha='center', fontsize=7)
    axes[0].text(i + w/2, v2 + 0.02, f'{v2:.3f}', ha='center', fontsize=7)

for i in range(5):
    axes[1].scatter(df['Recall'][i], df['Precision'][i], s=200, c=colors[i],
                   label=labels[i].replace('\n', ' '), zorder=5, edgecolors='black')
axes[1].set_xlabel('Recall')
axes[1].set_ylabel('Precision')
axes[1].set_title('Precision vs Recall')
axes[1].legend(fontsize=7)
axes[1].set_xlim(0, 1)
axes[1].set_ylim(0, 1)

base = df['mAP50'][0]
imps = [(v - base) / base * 100 for v in df['mAP50']]
bars = axes[2].bar(labels, imps, color=colors)
axes[2].set_ylabel('Improvement over Baseline (%)')
axes[2].set_title('mAP50 Improvement (%)')
axes[2].axhline(y=0, color='black', linewidth=0.5)
for bar, imp in zip(bars, imps):
    y = bar.get_height() + 0.3 if bar.get_height() >= 0 else bar.get_height() - 1.5
    axes[2].text(bar.get_x() + bar.get_width()/2., y,
                f'{imp:+.1f}%', ha='center', fontweight='bold', fontsize=8)

plt.tight_layout()
plt.savefig('experiment_comparison.png', dpi=150, bbox_inches='tight')
plt.show()

"""## Per-Class Breakdown"""

all_m = [m1, m2, m3, m4, m5]
exp_labels = ['Baseline', 'Arch Mod', 'Strategy', 'Full+Custom', 'Arch+Custom']

print("\nPer-Class mAP50-95 Breakdown")
print("="*90)
print(f"{'Class':<15}" + "".join(f"{l:<15}" for l in exp_labels))
print("-"*90)
for i, cls in enumerate(base_names):
    row = f"{cls:<15}"
    for m in all_m:
        if hasattr(m.box, 'maps') and i < len(m.box.maps):
            row += f"{m.box.maps[i]:<15.4f}"
        else:
            row += f"{'N/A':<15}"
    print(row)
print("="*90)

"""---
## Inference: Visualize Predictions
"""

import glob
from IPython.display import Image, display

# Find best model
for candidate in ['/content/runs/detect/soccer_results/exp5_arch_custom/weights/best.pt',
                   '/content/runs/detect/soccer_results/exp4_full_custom/weights/best.pt',
                  '/content/runs/detect/soccer_results/exp3_strategy/weights/best.pt']:
    if os.path.exists(candidate):
        best_path = candidate
        break

best_model = YOLO(best_path)
print(f"Using: {best_path}")

# Find test images
test_dir = os.path.join(BASE_PATH, 'test', 'images')
if not os.path.exists(test_dir) or len(os.listdir(test_dir)) == 0:
    test_dir = os.path.join(BASE_PATH, 'valid', 'images')

for img_name in sorted(os.listdir(test_dir))[:6]:
    best_model.predict(
        os.path.join(test_dir, img_name),
        conf=0.25, save=True,
        project='soccer_results', name='predictions', exist_ok=True,
    )

pred_images = sorted(glob.glob('soccer_results/predictions/*.jpg'))[:6]
for p in pred_images:
    print(f"\n{os.path.basename(p)}")
    display(Image(filename=p, width=600))

import glob
from IPython.display import Image, display

# Show prediction results
predict_dir = sorted(glob.glob('/content/runs/detect/soccer_results/predict*'))[-1]
pred_images = glob.glob(os.path.join(predict_dir, '*.jpg'))[:5]

for img_path in pred_images:
    print(f"\n{os.path.basename(img_path)}")
    display(Image(filename=img_path, width=600))